EZP-30882: As a developer I want to use custom Field Type as Content thumbnail
ezsystems/repository-forms pull request #326
Opened 2019-11-12 07:51 UTC by Nattfarinn

# Depends on: https://github.com/ezsystems/ezpublish-kernel/pull/2868

2019-11-12 08:40 UTC, ViniTou approved these changes

2019-11-12 08:40 UTC, ViniTou commented on lib/Form/Type/FieldDefinition/FieldDefinitionType.php
> +    /**
new line

2019-11-12 11:21 UTC, bdunogier commented
I'd change the commit message to what the patch actually does, but I'm not a developer anymore ;)

`Integrated the "isThumbnail" field definition option (EZP-30882)`

2019-12-11 14:40 UTC, alongosz requested changes
> I'd change the commit message to what the patch actually does, but I'm not a developer anymore ;)
> 
> `Integrated the "isThumbnail" field definition option (EZP-30882)`

Definitely, I need to distinguish this on the list of changes and later on when looking for something.
Though it should rather be:
> EZP-30882: Integrated the "isThumbnail" field definition option

Other remark:

2019-12-11 14:40 UTC, alongosz commented on bundle/Resources/config/services.yaml
> +            - '@eZ\Publish\Core\Repository\Strategy\ContentThumbnail\Field\ContentFieldStrategy'
Please create a service in Kernel which uses interface (API/SPI?) and use it here.

2019-12-16 10:52 UTC, Nattfarinn commented
Repository Forms is deprecated

2019-12-16 10:52 UTC, closed without merging